<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Rox\Module'                        => __DIR__ . '/Module.php',
    'Rox\Controller\DefaultControllerController' => __DIR__ . '/src/Rox/Controller/DefaultControllerController.php',
    'RoxTest\Framework\TestCase'        => __DIR__ . '/tests/Rox/Framework/TestCase.php',
    'RoxTest\SampleTest'                => __DIR__ . '/tests/Rox/SampleTest.php',
);
