<div class="col-md-3">
	<div class="panel-group" id="left-navigation">
	<?php $acl = $this->viewmodel()->getCurrent()->acl ?>
	<?php foreach ($pages as $resource => $page): ?>
		<?php if ($acl->isAllowed($this->loggedUser('type'), $resource)) :?>
		    <div class="panel panel-default">
					<div class="panel-heading">
						<a class="accordion-toggle" data-toggle="collapse"
							data-parent="#left-navigation" href="#collapse-<?= str_replace('/', '-', $resource); ?>"> <b><?= $page['label'] ?></b>
						</a>
					</div>
					<div id="collapse-<?= str_replace('/', '-', $resource); ?>"
						class="panel-collapse collapse<? //= ($page->isActive())?'in':''; ?>">
						<div class="panel-body">
							<ul class="nav nav-stacked">
		                        <?php foreach($page['pages'] as $realResource=>$content): ?>
		                        	<?php $realResource = explode(';',$realResource)[0]; ?>
	                            	<?php if ($acl->isAllowed($this->loggedUser('type'), $realResource, $content['action'])) :?>
		                                <?//= ($content['action']->isActive())?'<script>$("#collapse-'. $resource .'").collapse("show")</script>':'';?>
		                                <?php $paths = explode('/', $realResource)?>
		                                <?php $urlArray = ['controller' => $paths[1], 'action' => $content['action']]?>
		                                	<?php if(isset($content['id'])) :?>
		                                		<?php $urlArray['id'] = $content['id']; ?>
		                                	<?php endif;?>
		                                <li><a class="" href="<?= $this->url($paths[0] . '/default', $urlArray)?>"><?= $content['label']; ?></a></li>
	                                <?php endif; ?>
		                        <?php endforeach; ?>
		                    </ul>
						</div>
					</div>
				</div>
		<?php endif; ?>
<?php endforeach; ?>
</div>
</div>