<?php if ($this->pageCount): ?>
<?php
$params = isset($this->params)?$this->params:[];
$query = isset($this->query)?$this->query:[];
?>
        <ul class="pagination pagination-centered">
            
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <?php $query['page'] = $this->previous; ?>
                <li>
                    <a href="<?php echo $this->url($this->route, $params, ['query' => $query]); ?>">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a>
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                </li>
            <?php endif; ?>
            
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <?php $query['page'] = $page; ?>
                    <li>
                        <a href="<?php echo $this->url($this->route, $params, ['query' => $query]); ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <?php $query['page'] = $this->next; ?>
                <li>
                    <a href="<?php echo $this->url($this->route, $params, ['query' => $query]); ?>">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                     <a>
                     	<span class="glyphicon glyphicon-chevron-right"></span>
                     </a>
                </li>
            <?php endif; ?>
        </ul>
<?php endif; ?>