<?php if ($this->pageCount): ?>
<?php $params = isset($this->params)?$this->params:null; ?>
        <ul class="pagination pagination-centered">
            
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, $params); ?>?page=<?php echo $this->previous; ?>">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a>
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                </li>
            <?php endif; ?>
            
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route, $params);?>?page=<?php echo $page; ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, $params); ?>?page=<?php echo $this->next; ?>">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                     <a>
                     	<span class="glyphicon glyphicon-chevron-right"></span>
                     </a>
                </li>
            <?php endif; ?>
        </ul>
<?php endif; ?>