<?php
$class = sprintf('form-horizontal %s',$form->getAttribute('class'));
$form->setAttribute ( 'class', $class );
$form->prepare ();
$labelClass = sprintf ( 'col-lg-%s control-label', $labelColunms );
?>

<?= $this->form()->openTag($form)?>
<?php foreach ($form->getElements() as $element): ?>
	<?= $this->simpleFormRow($element) ?>
<?php endforeach; //FIXME is there a better way to handle fieldsets? maybe should we use a recursive solution? ?>

<?php foreach ($form->getFieldsets() as $name => $fieldset): ?>
    <?php foreach ($fieldset->getElements() as $element): ?>
    	<?= $this->simpleFormRow($element) ?>
    <?php endforeach; ?>
<?php endforeach;?>
<?php $submitLabel = isset($submitText)?$submitText:'Salvar'; ?>
	<div class="form-group">
		<div class="col-lg-offset-<?= $labelColunms ?> col-lg-<?= $colunms ?>">
			<button class="btn btn-success" type="submit"><?= $submitLabel ?></button>
			<button class="btn btn-warning" type="button" data-dismiss="modal">Cancelar</button>
		</div>
	</div>
<?= $this->form()->closeTag()?>