<?php
$class = sprintf('form-horizontal %s',$form->getAttribute('class'));
$form->setAttribute ( 'class', $class );
$form->prepare ();
$colunms = 12 - $labelColunms;
$options = ['label_colunms' => $labelColunms, 'element_colunms' => $colunms];
?>

<?= $this->form()->openTag($form)?>

<?php foreach ($form->getElements() as $element): ?>
	<?= $this->simpleFormRow($element, $options) ?>
<?php endforeach;?>

<?php $this->renderFieldsets($form->getFieldsets(), $options) ?>

<?php $submitLabel = isset($submitText)?$submitText:'Salvar'; ?>
	<div class="form-group">
		<div class="col-lg-offset-<?= $labelColunms ?> col-lg-<?= $colunms ?>">
			<button class="btn btn-success" type="submit"><?= $submitLabel ?></button>
			<button class="btn btn-warning" type="button" data-dismiss="modal">Cancelar</button>
		</div>
	</div>
<?= $this->form()->closeTag()?>