<?php if($element instanceof \Zend\Form\Element\Hidden || $element instanceof \Zend\Form\Element\Csrf): ?>
    <?= $this->formElement($element); ?>
<?php else: ?>
<div class="form-group <?= $hasError ?>">
    <?= $label; ?>
    <div class="col-lg-<?= $colunms ?>">
        <?= $prepend_html?>
        <div class="<?= $input_group ?>">
            <?= $prepend_addon ?>    
            <?= $this->formElement($element); ?>
            <?= $append_addon?>
        </div>
        <?= $append_html?>
        <span class="help-block form-error" style="<?= $display ?>"><?= $errors ?></span>
	</div>
</div>
<?php endif; ?>