<div class="form-group compound-form-row">
	<?php foreach ($elements as $element): ?>
		<div class="col-md-<?= $element['colunms'][1] ?> <?= $element['has_error'] ?>">
		<?= $element['label'] ?>
			<?php if(isset($element['prepend_addon'])): ?>
				<div class="input-group">
	            	<?= $element['prepend_addon'] ?>
            		<?= $this->formElement($element['element']); ?>
				</div>
			<?php else: ?>
				<?= $this->formElement($element['element']); ?>
			<?php endif;?>
			<span class="help-block form-error" style="<?= $element['display_errors'] ?>"><?= $element['errors'] ?></span>
		</div>
		
	<?php endforeach; ?>
</div>